"""init

Revision ID: f61bdb3b374e
Revises: 
Create Date: 2025-12-13 04:45:13.254408

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61bdb3b374e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名前'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='有効フラグ'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
